report_to_replacement_rules <- function(report, path = NULL) {
  #' Convert the output of `data_frame_report` to a csv file for editing.
  #' It is intended the user changes the `To` column to define desired
  #' replacements.
  #'
  #' @param report The `data.frame` generated by `data_frame_report`
  #' @param path File path for write.
  #'
  #' @return data.frame
  #'
  #' @export
  .frm <- report |>
    mutate(
      If = Sentence,
      From = Token,
      To = Token,
      .keep = "none"
    )

  if (is.null(path)) {
    return(.frm)
  }

  write.csv(.frm, path)
  .frm
}

load_replacement_rules <- function(object, parse = F) {
  #' Convert a set of `replacement_rules` (as defined with `report_to_replacement_rules`) to
  #' a function that can be used to modify a data frame.
  #'
  #' @param object The `replacement_rules` (can be a `data.frame`
  #'    or a path to a csv file containing the rules).
  #' @param parse Binary-flag.  If True the replacement function is parsed.
  #'
  #' @export
  UseMethod("load_replacement_rules")
}

load_replacement_rules.character <- function(object, parse = F) {
  #' @exportS3Method
  rules.frm <- read.csv(path)

  load_replacement_rules(rules.frm, parse)
}

load_replacement_rules.data.frame <- function(object, parse = F) {
  #' @exportS3Method

  parse_replacement_rules(object, parse)
}


parse_replacement_rules <- function(rules.frm, parse = F) {
  #' @importFrom dplyr group_by group_map
  #' @importFrom dplyr case_when
  #' @importFrom stringr str_replace_all str_detect

  .rules <- rules.frm |>
    mutate(
      From = escape_quote_mark(From),
      To = escape_quote_mark(To),
      If = escape_quote_mark(If),
      Replace = sprintf("stringr::str_replace_all('%s', '%s')", From, To)
    ) |>
    group_by(If) |>
    group_map(if_modify) |>
    simplify()

  .result <- sprintf(
    "function(.x) dplyr::case_when(
    %s,
    .default=.x
  )",
    paste0(.rules, collapse = ",\n")
  )

  if (parse) {
    .result <- parse(text = .result) |>
      eval()
  }

  .result
}


if_modify <- function(frm, group) {
  .if <- group$If

  .left <- sprintf("stringr::str_detect(.x, '%s')", .if)
  .right <- paste(c(".x", frm$Replace), collapse = " |> ")


  sprintf("%s ~ %s", .left, .right)
}

escape_quote_mark <- function(vec) {
  str_replace_all(vec, "'", "\\\\'")
}
